import { useState, useEffect } from 'react';
import axios from 'axios';
import { Cpu, ShieldCheck, AlertOctagon, HelpCircle, ShieldAlert } from 'lucide-react';
import SeverityBadge from '../components/SeverityBadge';

const BASE = 'http://localhost:8000/api';

export default function Reports() {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);

  useEffect(() => {
    axios.get(`${BASE}/reports`)
      .then((res) => {
        if (res.data && res.data.reports) {
          setReports(res.data.reports);
        }
        setLoading(false);
      })
      .catch(() => {
        setError(true);
        setLoading(false);
      });
  }, []);

  if (loading) {
    return (
      <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '400px' }}>
        <p style={{ color: 'var(--text-muted)' }}>Generating threat reports via AI model explanation engine...</p>
      </div>
    );
  }

  return (
    <div className="fade-in" style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
      <div>
        <h2 style={{ fontSize: '1.8rem', marginBottom: '8px' }}>AI Threat Reports</h2>
        <p style={{ color: 'var(--text-muted)' }}>
          Autonomous security analyst reports generated by Layer 8 (LLM explanation) to translate raw network metrics into response briefs.
        </p>
      </div>

      {reports.length > 0 ? (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
          {reports.map((report, idx) => {
            const llm = report.llm_report || {};
            const cves = report.related_cves || [];
            
            return (
              <div key={idx} className="card" style={{ padding: '32px', display: 'flex', flexDirection: 'column', gap: '20px' }}>
                {/* Header */}
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '12px', borderBottom: '1px solid var(--border-color)', paddingBottom: '16px' }}>
                  <div>
                    <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)', fontWeight: 600, display: 'block', marginBottom: '4px' }}>
                      SECURITY BRIEFING #{report.index}
                    </span>
                    <h3 style={{ fontSize: '1.5rem', display: 'flex', alignItems: 'center', gap: '8px' }}>
                      <AlertOctagon color="var(--color-danger)" size={22} />
                      <span>{report.attack_type} from {report.ip}</span>
                    </h3>
                  </div>
                  <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
                    <SeverityBadge severity={llm.severity || report.severity} />
                    <span className="badge" style={{ backgroundColor: 'rgba(88,166,255,0.1)', color: 'var(--color-primary)', border: '1px solid rgba(88,166,255,0.2)' }}>
                      Risk Fused: {report.confidence_pct}%
                    </span>
                  </div>
                </div>

                {/* Body Content */}
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '24px' }}>
                  
                  {/* Detailed Explanation */}
                  <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                    <h4 style={{ fontSize: '1rem', color: 'var(--color-primary)', fontWeight: 700 }}>AI Incident Explanation</h4>
                    <p style={{ fontSize: '0.9rem', color: 'var(--text-main)', lineHeight: 1.6 }}>
                      {llm.explanation || 'No explanation summary could be generated.'}
                    </p>

                    <h4 style={{ fontSize: '1rem', color: 'var(--color-danger)', fontWeight: 700, marginTop: '8px' }}>Risk Assessment</h4>
                    <p style={{ fontSize: '0.9rem', color: 'var(--text-muted)', lineHeight: 1.6 }}>
                      {llm.why_dangerous || 'N/A'}
                    </p>
                  </div>

                  {/* Mitigation and Model Agreement */}
                  <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                    <h4 style={{ fontSize: '1rem', color: 'var(--color-success)', fontWeight: 700 }}>Recommended Actions</h4>
                    <div style={{
                      backgroundColor: 'rgba(63, 185, 80, 0.04)',
                      border: '1px solid rgba(63, 185, 80, 0.1)',
                      borderRadius: '8px',
                      padding: '16px',
                      fontSize: '0.88rem',
                      lineHeight: 1.6
                    }}>
                      {llm.mitigation ? (
                        <div style={{ whiteSpace: 'pre-line' }}>{llm.mitigation}</div>
                      ) : (
                        <p style={{ color: 'var(--text-muted)' }}>1. Isolate the target machine.<br/>2. Block Source IP.<br/>3. Conduct firewall audits.</p>
                      )}
                    </div>

                    <div style={{ marginTop: '8px' }}>
                      <h4 style={{ fontSize: '0.9rem', color: 'var(--color-secondary)', fontWeight: 700, marginBottom: '6px' }}>Consensus Summary</h4>
                      <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>
                        <strong>Model Agreement:</strong> {llm.model_agreement || 'N/A'}
                      </p>
                    </div>
                  </div>

                </div>

                {/* Threat Intel / CVE Section */}
                <div style={{
                  backgroundColor: 'rgba(255, 255, 255, 0.02)',
                  border: '1px solid var(--border-color)',
                  borderRadius: '8px',
                  padding: '16px 20px',
                  display: 'flex',
                  flexDirection: 'column',
                  gap: '10px'
                }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '8px' }}>
                    <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)', fontWeight: 600 }}>THREAT INTEL REPUTATION</span>
                    <span style={{ fontSize: '0.8rem', fontWeight: 700, color: report.ip_is_known_bad ? 'var(--color-danger)' : 'var(--text-muted)' }}>
                      {report.ip_reputation?.reason || 'No matches in local blocklists'}
                    </span>
                  </div>
                  
                  {cves.length > 0 && (
                    <div style={{ borderTop: '1px solid rgba(48,54,61,0.3)', paddingTop: '10px', marginTop: '4px' }}>
                      <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)', fontWeight: 600, display: 'block', marginBottom: '8px' }}>
                        RELATED CVE MAPS
                      </span>
                      <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px' }}>
                        {cves.map((cve, idx) => (
                          <div key={idx} style={{
                            backgroundColor: 'rgba(88,166,255,0.05)',
                            border: '1px solid rgba(88,166,255,0.15)',
                            borderRadius: '4px',
                            padding: '6px 12px',
                            fontSize: '0.75rem'
                          }}>
                            <strong style={{ color: 'var(--color-primary)' }}>{cve.id}</strong> — {cve.desc}
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>

              </div>
            );
          })}
        </div>
      ) : (
        <div className="card" style={{ textAlign: 'center', padding: '60px 20px', color: 'var(--text-muted)', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '16px' }}>
          <ShieldCheck size={48} color="var(--color-success)" style={{ opacity: 0.8 }} />
          <h3>No Threat Reports Available</h3>
          <p style={{ maxWidth: '500px', margin: '0 auto', fontSize: '0.9rem' }}>
            No security event reports are available because no intrusions were identified in the uploaded log dataset.
          </p>
        </div>
      )}
    </div>
  );
}
